### ISSUE TITLE
VS Code does not use this Editor when opening .8xp files

### ISSUE THREAD

**Issue by KeyboardG** [beastmatser/ti-basic-autocomplete#1]
On latest VS Code on Windows 10 after installing this extension and opening any .8xp file VS Code alerts that file is binary, do you wish to open anyway. When selecting yes, only the generic text editor is available.

Are there other prerequisites?

Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.1904
![VSCodeError](https://user-images.githubusercontent.com/1760835/157071390-9b8bf5f4-2851-4642-809d-8bdde792e968.png)
![VSCodeError2](https://user-images.githubusercontent.com/1760835/157071471-e6f3c78f-d1e5-4197-845c-935186c1255d.png)
4

**Comment by beastmatser** [comment]
As it turns out the `.8xp` file extension is a compiled file, the app ti-connect can open these sort of files and display those as text. So I thought I could use this file extension as well, but unfortunately this is not really the case.

Workaround:
Open the file with the ti-connect app en copy the text into a file in vscode and set the language mode to `8xp`, if you want to upload your code to the calculator you should copy the text in vscode into the ti-connect app and then upload it (do not use the same file, it will overwrite the text by the binaries).

If you need anymore help, just let me know, I am available on Discord ([here](https://discord.com/users/774593264170958872)) if you would like to discuss some more things or if you want me to clarify further

I also will put this into the readme, thank you for letting me know, happy coding :)

**Comment by beastmatser** [comment]
I added the notes in the [wiki](https://github.com/beastmatser/ti-basic-autocomplete/wiki), thank you for your contribution!
